# Generated by Django 3.1.7 on 2021-03-04 23:53

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add Additional Text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock()), ('service_cards', wagtail.core.blocks.StructBlock([('service_cards_title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('service_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('service_type', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('service_description', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_to_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Button to a page on your site', required=False)), ('button_to_url', wagtail.core.blocks.URLBlock(help_text='Button to any website using the URL link', required=False))])))]))], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Flexed Home Page',
                'verbose_name_plural': 'Flexed Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add Additional Text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock()), ('service_cards', wagtail.core.blocks.StructBlock([('service_cards_title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('service_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('service_type', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('service_description', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_to_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Button to a page on your site', required=False)), ('button_to_url', wagtail.core.blocks.URLBlock(help_text='Button to any website using the URL link', required=False))])))]))], blank=True, null=True),
        ),
    ]
