# Generated by Django 3.1.7 on 2021-03-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_number',
            field=models.IntegerField(blank=True, default='123456789'),
            preserve_default=False,
        ),
    ]
