# Generated by Django 3.1.7 on 2021-03-07 12:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20210306_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
