# Generated by Django 3.1.7 on 2021-03-05 10:43

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('home_page_title', models.CharField(blank=True, max_length=50, null=True)),
                ('home_page_subtitle', wagtail.core.fields.RichTextField()),
                ('home_page_panels', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add Additional Text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock()), ('service_cards', wagtail.core.blocks.StructBlock([('service_cards_title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('service_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('service_type', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('service_description', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_to_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Button to a page on your site', required=False)), ('button_to_url', wagtail.core.blocks.URLBlock(help_text='Button to any website using the URL link', required=False))])))]))], blank=True, null=True)),
                ('home_page_cta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('top_home_page_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
