# Generated by Django 3.1.7 on 2021-03-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_tab_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='tab_title',
            new_name='page_title',
        ),
    ]
