# Generated by Django 3.1.7 on 2021-03-03 16:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_auto_20210303_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='page_title',
            new_name='home_page_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_page_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_page_subtitle',
            field=wagtail.core.fields.RichTextField(default='Test Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_home_page_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
